[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[context.production.environment]
  NEXT_PUBLIC_ENV = "production"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ENV = "preview"
